name: 'Tic_Tac_Toe_Deployment'
description: 'Deploy to AWS Elastic Beanstalk'
inputs:
  aws_access_key:
    description: 'AWS access key'
    required: true
  aws_secret_key:
    description: 'AWS secret access key'
    required: true
  application_name:
    description: 'Name of the Elastic Beanstalk application'
    required: true
  environment_name:
    description: 'Name of the Elastic Beanstalk environment'
    required: true
  version_label:
    description: 'Version label for the deployment'
    required: true
  region:
    description: 'AWS region'
    required: true
  deployment_package:
    description: 'Path to the deployment package zip file'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
